#include "params.h"

#define CRYPTO_SECRETKEYBYTES NTRU_SECRETKEYBYTES
#define CRYPTO_PUBLICKEYBYTES NTRU_PUBLICKEYBYTES
#define CRYPTO_CIPHERTEXTBYTES NTRU_BYTES
#define CRYPTO_SHAREDKEYBYTES NTRU_SHAREDKEYBYTES
